Repository wirecard/woocommerce-ee, pull requests merged in 2020-08, with the labels that each got.

#418 Tpwdcee 7385 phraseapp configuration
  .github/workflows/run-phraseapp-pull.yml
  .travis.yml
  Rakefile
Labels: no-release, ready for merge

#424 Add new stage to install and setup xonsh
  .github/workflows/run-acceptance-tests.yml
Labels: no-release

#423 Enable possibility to overwrite provided templates
  wirecard-woocommerce-extension/Test/stubs/wp-functions.php
  wirecard-woocommerce-extension/Test/unit/classes/helper/utest-class-template-helper.php
  wirecard-woocommerce-extension/classes/helper/class-template-helper.php
  wirecard-woocommerce-extension/constants/woocommerce-wirecard-definitions.php
  wirecard-woocommerce-extension/templates/credit-card-form.php
  wirecard-woocommerce-extension/templates/credit-card-save-for-later.php
  wirecard-woocommerce-extension/templates/credit-card-submit.php
  wirecard-woocommerce-extension/templates/credit-card-vault.php
  wirecard-woocommerce-extension/templates/spinner.php
Labels: ready for merge

#426 Codacy improvements.
  .github/workflows/run_cs_unit_coverage.yml
  phpcs.xml
  wirecard-woocommerce-extension/Test/stubs/wc-functions.php
  wirecard-woocommerce-extension/Test/stubs/wc-order.php
  wirecard-woocommerce-extension/Test/stubs/wc-product.php
  wirecard-woocommerce-extension/Test/stubs/wc-session.php
  wirecard-woocommerce-extension/Test/stubs/wc-settings-api.php
  wirecard-woocommerce-extension/Test/stubs/wc-tax.php
  wirecard-woocommerce-extension/Test/stubs/wp-functions.php
  wirecard-woocommerce-extension/Test/stubs/wpdb.php
  wirecard-woocommerce-extension/Test/unit/classes/admin/utest-class-wirecard-transaction-factory.php
  wirecard-woocommerce-extension/Test/unit/classes/handler/utest-class-wirecard-response-handler.php
  wirecard-woocommerce-extension/Test/unit/classes/helper/utest-class-additional-information.php
  wirecard-woocommerce-extension/Test/unit/classes/helper/utest-class-admin-message.php
  wirecard-woocommerce-extension/Test/unit/classes/helper/utest-class-basket-item-helper.php
  wirecard-woocommerce-extension/Test/unit/classes/helper/utest-class-credit-card-vault.php
  wirecard-woocommerce-extension/Test/unit/classes/helper/utest-class-money-formatter.php
  wirecard-woocommerce-extension/Test/unit/classes/helper/utest-class-template-helper.php
  wirecard-woocommerce-extension/Test/unit/classes/includes/utest-class-wc-gateway-wirecard-creditcard.php
  wirecard-woocommerce-extension/Test/unit/classes/includes/utest-class-wc-gateway-wirecard-eps.php
  wirecard-woocommerce-extension/Test/unit/classes/includes/utest-class-wc-gateway-wirecard-giropay.php
  wirecard-woocommerce-extension/Test/unit/classes/includes/utest-class-wc-gateway-wirecard-guaranteed-invoice-ratepay.php
  wirecard-woocommerce-extension/Test/unit/classes/includes/utest-class-wc-gateway-wirecard-ideal.php
  wirecard-woocommerce-extension/Test/unit/classes/includes/utest-class-wc-gateway-wirecard-paypal.php
  wirecard-woocommerce-extension/Test/unit/classes/includes/utest-class-wc-gateway-wirecard-sepa.php
  wirecard-woocommerce-extension/assets/js/admin/plugin_admin.js
  wirecard-woocommerce-extension/assets/js/creditcard.js
  wirecard-woocommerce-extension/assets/js/sepa.js
  wirecard-woocommerce-extension/assets/styles/admin.css
  wirecard-woocommerce-extension/assets/styles/frontend.css
  wirecard-woocommerce-extension/assets/styles/loader.css
  wirecard-woocommerce-extension/classes/admin/class-wirecard-settings.php
  wirecard-woocommerce-extension/classes/admin/class-wirecard-transaction-factory.php
  wirecard-woocommerce-extension/classes/handler/class-wirecard-handler.php
  wirecard-woocommerce-extension/classes/handler/class-wirecard-notification-handler.php
  wirecard-woocommerce-extension/classes/handler/class-wirecard-transaction-handler.php
  wirecard-woocommerce-extension/classes/helper/class-upgrade-helper.php
  wirecard-woocommerce-extension/classes/includes/class-wc-gateway-wirecard-alipay-crossborder.php
  wirecard-woocommerce-extension/classes/includes/class-wc-gateway-wirecard-creditcard.php
  wirecard-woocommerce-extension/classes/includes/class-wc-gateway-wirecard-eps.php
  wirecard-woocommerce-extension/classes/includes/class-wc-gateway-wirecard-giropay.php
  wirecard-woocommerce-extension/classes/includes/class-wc-gateway-wirecard-guaranteed-invoice-ratepay.php
  wirecard-woocommerce-extension/classes/includes/class-wc-gateway-wirecard-ideal.php
  wirecard-woocommerce-extension/classes/includes/class-wc-gateway-wirecard-pay-by-bank-app.php
  wirecard-woocommerce-extension/classes/includes/class-wc-gateway-wirecard-paypal.php
  wirecard-woocommerce-extension/classes/includes/class-wc-gateway-wirecard-sepa-credit-transfer.php
  wirecard-woocommerce-extension/classes/includes/class-wc-gateway-wirecard-sepa-direct-debit.php
  wirecard-woocommerce-extension/classes/includes/class-wc-wirecard-payment-gateway.php
  wirecard-woocommerce-extension/classes/upgrade/extension-upgrade-hook.php
  wirecard-woocommerce-extension/woocommerce-wirecard-payment-gateway.php
Labels: ready for review

#430 Show order number in transaction table.
  wirecard-woocommerce-extension/classes/admin/class-wirecard-transaction-factory.php
Labels: ready for approval

#429 Increase Security for input fields
  wirecard-woocommerce-extension/assets/js/admin/plugin_admin.js
  wirecard-woocommerce-extension/assets/styles/admin.css
  wirecard-woocommerce-extension/classes/includes/class-wc-gateway-wirecard-alipay-crossborder.php
  wirecard-woocommerce-extension/classes/includes/class-wc-gateway-wirecard-creditcard.php
  wirecard-woocommerce-extension/classes/includes/class-wc-gateway-wirecard-eps.php
  wirecard-woocommerce-extension/classes/includes/class-wc-gateway-wirecard-giropay.php
  wirecard-woocommerce-extension/classes/includes/class-wc-gateway-wirecard-guaranteed-invoice-ratepay.php
  wirecard-woocommerce-extension/classes/includes/class-wc-gateway-wirecard-ideal.php
  wirecard-woocommerce-extension/classes/includes/class-wc-gateway-wirecard-pay-by-bank-app.php
  wirecard-woocommerce-extension/classes/includes/class-wc-gateway-wirecard-paypal.php
  wirecard-woocommerce-extension/classes/includes/class-wc-gateway-wirecard-poipia.php
  wirecard-woocommerce-extension/classes/includes/class-wc-gateway-wirecard-sepa-credit-transfer.php
  wirecard-woocommerce-extension/classes/includes/class-wc-gateway-wirecard-sepa-direct-debit.php
  wirecard-woocommerce-extension/classes/includes/class-wc-gateway-wirecard-sofort.php
  wirecard-woocommerce-extension/classes/includes/class-wc-wirecard-payment-gateway.php
  wirecard-woocommerce-extension/woocommerce-wirecard-payment-gateway.php
Labels: ready for approval

#432 Add github action for branch name validation
  .github/pr_lint.json
  .github/prlint.json
  .github/workflows/pr-lint.yml
Labels: no-release
