Repository wirecard/woocommerce-ee, pull requests merged in 2020-04, with the labels that each got.

#351 Tpwdcee 6235 configuration
  .bin/run-ui-tests.sh
  .bin/send-notify.sh
  .bin/setup-and-run-ui-tests.sh
  .bin/start-ngrok.sh
  .bin/start-shopsystem.sh
  .bin/upload-logs-and-notify.sh
  .env
  .travis.yml
  Dockerfile
  Dockerfile_codeception
  docker-compose.yml
  wirecard-woocommerce-extension/tests/_data/CustomerData.json
  wirecard-woocommerce-extension/tests/_data/GiropayData.json
  wirecard-woocommerce-extension/tests/_data/PaymentMethodData.json
  wirecard-woocommerce-extension/tests/_data/configure_payment_method_db.php
  wirecard-woocommerce-extension/tests/_data/gateway_configs/creditcard.json
  wirecard-woocommerce-extension/tests/_data/gateway_configs/giropay.json
  wirecard-woocommerce-extension/tests/_data/gateway_configs/paypal.json
  wirecard-woocommerce-extension/tests/_support/AcceptanceTester.php
  wirecard-woocommerce-extension/tests/_support/Helper/Acceptance.php
  wirecard-woocommerce-extension/tests/_support/Helper/DbHelper.php
  wirecard-woocommerce-extension/tests/_support/Helper/PhpBrowserAPI.php
  wirecard-woocommerce-extension/tests/_support/Page/Base.php
  wirecard-woocommerce-extension/tests/_support/Page/Cart.php
  wirecard-woocommerce-extension/tests/_support/Page/Checkout.php
  wirecard-woocommerce-extension/tests/_support/Page/GiropayPayment.php
  wirecard-woocommerce-extension/tests/_support/Page/OrderReceived.php
  wirecard-woocommerce-extension/tests/_support/Page/PayPalLogIn.php
  wirecard-woocommerce-extension/tests/_support/Page/PayPalReview.php
  wirecard-woocommerce-extension/tests/_support/Page/Product.php
  wirecard-woocommerce-extension/tests/_support/Page/Shop.php
  wirecard-woocommerce-extension/tests/_support/Page/Verified.php
  wirecard-woocommerce-extension/tests/acceptance.suite.yml
  wirecard-woocommerce-extension/tests/acceptance/CreditCard3DSAuthorizationHappyPath.feature
  wirecard-woocommerce-extension/tests/acceptance/CreditCard3DSPurchaseHappyPath.feature
  wirecard-woocommerce-extension/tests/acceptance/CreditCardNon3DSAuthorizationHappyPath.feature
  wirecard-woocommerce-extension/tests/acceptance/CreditCardNon3DSPurchaseHappyPath.feature
  wirecard-woocommerce-extension/tests/acceptance/GiropayPurchaseHappyPath.feature
  wirecard-woocommerce-extension/tests/acceptance/PayPalPurchaseHappyPath.feature
Labels: no-release, ready for approval

#354 Substitute alipay-xborder logo
  wirecard-woocommerce-extension/assets/images/alipay-xborder.png
Labels: ready for merge

#355 Tpwdcee 6403 configuration
  .bin/setup-and-run-ui-tests.sh
  .bin/start-ngrok.sh
  .bin/start-shopsystem.sh
  .travis.yml
  docker-compose.yml
Labels: no-release, ready for approval

#356 Add change release version GitHub action
  .github/workflows/change-release-version.yml
Labels: no-release, ready for approval

#362 Tpwdcee 6146 configuration
  .github/workflows/run_cs_unit_coverage.yml
  codeception.yml
  wirecard-woocommerce-extension/codeception.yml
  wirecard-woocommerce-extension/tests/_support/Helper/Unit.php
  wirecard-woocommerce-extension/tests/_support/UnitTester.php
  wirecard-woocommerce-extension/tests/unit.suite.yml
  wirecard-woocommerce-extension/tests/unit/WC_Gateway_Wirecard_Basket_Item_UtestTest.php
  wirecard-woocommerce-extension/tests/unit/bootstrap.php
Labels: no-release, ready for merge

#364 Add dependabot to PR lint
  .github/pr-labeler.yml
  .github/prlint.json
Labels: no-release

#365 Add github action to validate travis file
  .github/workflows/validate-travis-file.yml
Labels: no-release

#366 Use Wirecard GitHub actions and expand PR labeler
  .github/pr-labeler.yml
  .github/workflows/change-release-version.yml
  .github/workflows/run_cs_unit_coverage.yml
Labels: no-release
