Repository wirecard/woocommerce-ee, pull requests merged in 2020-06, with the labels that each got.

#384 Update checkout post_form response status
  wirecard-woocommerce-extension/classes/handler/class-wirecard-callback.php
Labels: ready for merge

#382 Add workflow to automatically create PR from RC branch
  .github/workflows/create-pull-request-for-rc-branch.yml
Labels: no-release, ready for approval, ready for merge

#383 Remove Livezilla chat support
  wirecard-woocommerce-extension/classes/admin/class-wirecard-settings.php
  wirecard-woocommerce-extension/woocommerce-wirecard-payment-gateway.php
Labels: ready for approval

#379 Add PSD2 hint in phrase app translation files and admin credit card view
  wirecard-woocommerce-extension/classes/includes/class-wc-gateway-wirecard-creditcard.php
  wirecard-woocommerce-extension/languages/wirecard-woocommerce-extension-cs_CZ.mo
  wirecard-woocommerce-extension/languages/wirecard-woocommerce-extension-cs_CZ.po
  wirecard-woocommerce-extension/languages/wirecard-woocommerce-extension-de_DE.mo
  wirecard-woocommerce-extension/languages/wirecard-woocommerce-extension-de_DE.po
  wirecard-woocommerce-extension/languages/wirecard-woocommerce-extension-en_US.mo
  wirecard-woocommerce-extension/languages/wirecard-woocommerce-extension-en_US.po
  wirecard-woocommerce-extension/languages/wirecard-woocommerce-extension-fr_FR.mo
  wirecard-woocommerce-extension/languages/wirecard-woocommerce-extension-fr_FR.po
  wirecard-woocommerce-extension/languages/wirecard-woocommerce-extension-id_ID.mo
  wirecard-woocommerce-extension/languages/wirecard-woocommerce-extension-id_ID.po
  wirecard-woocommerce-extension/languages/wirecard-woocommerce-extension-ja.mo
  wirecard-woocommerce-extension/languages/wirecard-woocommerce-extension-ja.po
  wirecard-woocommerce-extension/languages/wirecard-woocommerce-extension-ko_KR.mo
  wirecard-woocommerce-extension/languages/wirecard-woocommerce-extension-ko_KR.po
  wirecard-woocommerce-extension/languages/wirecard-woocommerce-extension-nl_NL.mo
  wirecard-woocommerce-extension/languages/wirecard-woocommerce-extension-nl_NL.po
  wirecard-woocommerce-extension/languages/wirecard-woocommerce-extension-pl_PL.mo
  wirecard-woocommerce-extension/languages/wirecard-woocommerce-extension-pl_PL.po
  wirecard-woocommerce-extension/languages/wirecard-woocommerce-extension-sk_SK.mo
  wirecard-woocommerce-extension/languages/wirecard-woocommerce-extension-sk_SK.po
  wirecard-woocommerce-extension/languages/wirecard-woocommerce-extension-zh_CN.mo
  wirecard-woocommerce-extension/languages/wirecard-woocommerce-extension-zh_CN.po
  wirecard-woocommerce-extension/languages/wirecard-woocommerce-extension-zh_TW.mo
  wirecard-woocommerce-extension/languages/wirecard-woocommerce-extension-zh_TW.po
  wirecard-woocommerce-extension/languages/wirecard-woocommerce-extension.pot
Labels: ready for merge

#386 Use subsite prefix instead of global site prefix in a multisite environment
  wirecard-woocommerce-extension/classes/admin/class-wirecard-transaction-factory.php
  wirecard-woocommerce-extension/classes/upgrade/extension-upgrade-hook.php
  wirecard-woocommerce-extension/classes/upgrade/vault-upgrade.php
  wirecard-woocommerce-extension/woocommerce-wirecard-payment-gateway.php
Labels: no-release

#385 Get plugin names instead of install time
  wirecard-woocommerce-extension/woocommerce-wirecard-payment-gateway.php
Labels: no-release

#387 Update payment method name in admin transactions view
  wirecard-woocommerce-extension/classes/admin/class-wirecard-transaction-factory.php
  wirecard-woocommerce-extension/classes/includes/class-wc-wirecard-payment-gateway.php
  wirecard-woocommerce-extension/languages/wirecard-woocommerce-extension-fr_FR.mo
Labels: ready for approval

#388 Remove ui scripts and docker files
  .bin/generate-release-package.sh
  .bin/run-ui-tests.sh
  .bin/send-notify.sh
  .bin/setup-and-run-ui-tests.sh
  .bin/start-ngrok.sh
  .bin/start-shopsystem.sh
  .bin/upload-logs-and-notify.sh
  .env
  .github/workflows/run-acceptance-tests.yml
  .travis.yml
  Dockerfile
  Dockerfile_codeception
  docker-compose.yml
Labels: no-release, ready for approval

#404 Set orderNr to be sent always
  wirecard-woocommerce-extension/Test/unit/classes/helper/utest-class-additional-information.php
  wirecard-woocommerce-extension/classes/helper/class-additional-information.php
  wirecard-woocommerce-extension/classes/includes/class-wc-wirecard-payment-gateway.php
Labels: ready for merge

#401 Tpwdcee 6081 feature
  wirecard-woocommerce-extension/Test/unit/classes/helper/utest-class-additional-information.php
  wirecard-woocommerce-extension/classes/helper/class-additional-information.php
  wirecard-woocommerce-extension/classes/includes/class-wc-gateway-wirecard-paypal.php
Labels: ready for review
