Repository wirecard/woocommerce-ee, pull requests merged in 2020-03, with the labels that each got.

#338 Use Github Actions to deploy to Wordpress
  .bin/svn-blacklist.txt
  .bin/upload-to-marketplace.sh
  .github/workflows/create_release.yml
  .travis.yml
  wirecard-woocommerce-extension/.distignore
Labels: no-release, ready for approval

#341 Remove auto shop version update
  .travis.yml
Labels: no-release

#339 Substitute hardcoded credentials and substract payment credentials config
  composer.json
  wirecard-woocommerce-extension/classes/helper/class-credentials-loader.php
  wirecard-woocommerce-extension/classes/includes/class-wc-gateway-wirecard-alipay-crossborder.php
  wirecard-woocommerce-extension/classes/includes/class-wc-gateway-wirecard-creditcard.php
  wirecard-woocommerce-extension/classes/includes/class-wc-gateway-wirecard-eps.php
  wirecard-woocommerce-extension/classes/includes/class-wc-gateway-wirecard-giropay.php
  wirecard-woocommerce-extension/classes/includes/class-wc-gateway-wirecard-guaranteed-invoice-ratepay.php
  wirecard-woocommerce-extension/classes/includes/class-wc-gateway-wirecard-ideal.php
  wirecard-woocommerce-extension/classes/includes/class-wc-gateway-wirecard-pay-by-bank-app.php
  wirecard-woocommerce-extension/classes/includes/class-wc-gateway-wirecard-paypal.php
  wirecard-woocommerce-extension/classes/includes/class-wc-gateway-wirecard-poipia.php
  wirecard-woocommerce-extension/classes/includes/class-wc-gateway-wirecard-sepa-credit-transfer.php
  wirecard-woocommerce-extension/classes/includes/class-wc-gateway-wirecard-sepa-direct-debit.php
  wirecard-woocommerce-extension/classes/includes/class-wc-gateway-wirecard-sofort.php
  wirecard-woocommerce-extension/classes/includes/class-wc-wirecard-payment-gateway.php
  wirecard-woocommerce-extension/credentials_config.xml
  wirecard-woocommerce-extension/woocommerce-wirecard-payment-gateway.php
Labels: ready for merge

#346 Fix missing translation for order table header state filers
  wirecard-woocommerce-extension/languages/wirecard-woocommerce-extension-de_DE.mo
  wirecard-woocommerce-extension/languages/wirecard-woocommerce-extension-de_DE.po
  wirecard-woocommerce-extension/languages/wirecard-woocommerce-extension-en_US.mo
  wirecard-woocommerce-extension/languages/wirecard-woocommerce-extension-en_US.po
  wirecard-woocommerce-extension/languages/wirecard-woocommerce-extension-fr_FR.mo
  wirecard-woocommerce-extension/languages/wirecard-woocommerce-extension-fr_FR.po
  wirecard-woocommerce-extension/languages/wirecard-woocommerce-extension-id_ID.mo
  wirecard-woocommerce-extension/languages/wirecard-woocommerce-extension-id_ID.po
  wirecard-woocommerce-extension/languages/wirecard-woocommerce-extension-ja.mo
  wirecard-woocommerce-extension/languages/wirecard-woocommerce-extension-ja.po
  wirecard-woocommerce-extension/languages/wirecard-woocommerce-extension-ko_KR.mo
  wirecard-woocommerce-extension/languages/wirecard-woocommerce-extension-ko_KR.po
  wirecard-woocommerce-extension/languages/wirecard-woocommerce-extension-pl_PL.mo
  wirecard-woocommerce-extension/languages/wirecard-woocommerce-extension-pl_PL.po
  wirecard-woocommerce-extension/languages/wirecard-woocommerce-extension-zh_CN.mo
  wirecard-woocommerce-extension/languages/wirecard-woocommerce-extension-zh_CN.po
  wirecard-woocommerce-extension/languages/wirecard-woocommerce-extension-zh_TW.mo
  wirecard-woocommerce-extension/languages/wirecard-woocommerce-extension-zh_TW.po
  wirecard-woocommerce-extension/languages/wirecard-woocommerce-extension.pot
  wirecard-woocommerce-extension/woocommerce-wirecard-payment-gateway.php
Labels: ready for review

#342 Rc 3.2.0 minor
  .github/workflows/run_cs_unit_coverage.yml
  CHANGELOG.md
  SHOPVERSIONS
  composer.json
  wirecard-woocommerce-extension/classes/helper/class-credentials-loader.php
  wirecard-woocommerce-extension/classes/includes/class-wc-gateway-wirecard-alipay-crossborder.php
  wirecard-woocommerce-extension/classes/includes/class-wc-gateway-wirecard-creditcard.php
  wirecard-woocommerce-extension/classes/includes/class-wc-gateway-wirecard-eps.php
  wirecard-woocommerce-extension/classes/includes/class-wc-gateway-wirecard-giropay.php
  wirecard-woocommerce-extension/classes/includes/class-wc-gateway-wirecard-guaranteed-invoice-ratepay.php
  wirecard-woocommerce-extension/classes/includes/class-wc-gateway-wirecard-ideal.php
  wirecard-woocommerce-extension/classes/includes/class-wc-gateway-wirecard-pay-by-bank-app.php
  wirecard-woocommerce-extension/classes/includes/class-wc-gateway-wirecard-paypal.php
  wirecard-woocommerce-extension/classes/includes/class-wc-gateway-wirecard-poipia.php
  wirecard-woocommerce-extension/classes/includes/class-wc-gateway-wirecard-sepa-credit-transfer.php
  wirecard-woocommerce-extension/classes/includes/class-wc-gateway-wirecard-sepa-direct-debit.php
  wirecard-woocommerce-extension/classes/includes/class-wc-gateway-wirecard-sofort.php
  wirecard-woocommerce-extension/classes/includes/class-wc-wirecard-payment-gateway.php
  wirecard-woocommerce-extension/credentials_config.xml
  wirecard-woocommerce-extension/languages/wirecard-woocommerce-extension-de_DE.mo
  wirecard-woocommerce-extension/languages/wirecard-woocommerce-extension-de_DE.po
  wirecard-woocommerce-extension/languages/wirecard-woocommerce-extension-en_US.mo
  wirecard-woocommerce-extension/languages/wirecard-woocommerce-extension-en_US.po
  wirecard-woocommerce-extension/languages/wirecard-woocommerce-extension-fr_FR.mo
  wirecard-woocommerce-extension/languages/wirecard-woocommerce-extension-fr_FR.po
  wirecard-woocommerce-extension/languages/wirecard-woocommerce-extension-id_ID.mo
  wirecard-woocommerce-extension/languages/wirecard-woocommerce-extension-id_ID.po
  wirecard-woocommerce-extension/languages/wirecard-woocommerce-extension-ja.mo
  wirecard-woocommerce-extension/languages/wirecard-woocommerce-extension-ja.po
  wirecard-woocommerce-extension/languages/wirecard-woocommerce-extension-ko_KR.mo
  wirecard-woocommerce-extension/languages/wirecard-woocommerce-extension-ko_KR.po
  wirecard-woocommerce-extension/languages/wirecard-woocommerce-extension-pl_PL.mo
  wirecard-woocommerce-extension/languages/wirecard-woocommerce-extension-pl_PL.po
  wirecard-woocommerce-extension/languages/wirecard-woocommerce-extension-zh_CN.mo
  wirecard-woocommerce-extension/languages/wirecard-woocommerce-extension-zh_CN.po
  wirecard-woocommerce-extension/languages/wirecard-woocommerce-extension-zh_TW.mo
  wirecard-woocommerce-extension/languages/wirecard-woocommerce-extension-zh_TW.po
  wirecard-woocommerce-extension/languages/wirecard-woocommerce-extension.pot
  wirecard-woocommerce-extension/readme.txt
  wirecard-woocommerce-extension/woocommerce-wirecard-payment-gateway.php
Labels: minor

#348 Hotfix: archive size for partners
  CHANGELOG.md
  SHOPVERSIONS
  wirecard-woocommerce-extension/readme.txt
  wirecard-woocommerce-extension/woocommerce-wirecard-payment-gateway.php
Labels: patch, ready for merge
