Repository wirecard/woocommerce-ee, pull requests merged in 2020-05, with the labels that each got.

#370 Remove SHOPVERSIONS and add compose dry run for unit tests
  .github/workflows/run_cs_unit_coverage.yml
  .travis.yml
  SHOPVERSIONS
Labels: no-release

#371 Update 'validate travis' pipeline to run only on travis file change
  .github/workflows/validate-travis-file.yml
Labels: no-release

#372 Add github action for checking release notes in changelog file
  .github/workflows/changelog-comments-reminder-action.yml
Labels: no-release, ready for merge

#373 Prepare automatic version update from single point of truth
  .bin/compatible-shop-releases.txt
  .bin/get-latest-shop-release-versions.sh
  .bin/new-compatible-shop-releases.txt
  .bin/setup-and-run-ui-tests.sh
  .bin/start-ngrok.sh
  .bin/start-shopsystem.sh
  .bin/update-shop-release-versions.sh
  .github/workflows/changelog-comments-reminder-action.yml
  .github/workflows/update-release-information.yml
  .travis.yml
  Dockerfile
  wirecard-woocommerce-extension/readme.txt
Labels: no-release, ready for review
